# Header
menu:
  Home: /
  About: /about
  Archives: /archives

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts

# Miscellaneous
google_analytics: UA-64687025-1
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
